In [48]:
import numpy as np
alpha = 0.3
k = 2 # 1 < k < 15
rng = np.random.default_rng()
def compute_number_of_infected(alpha, k, rng=rng, x0=1):
    infected = np.zeros(k).astype(bool)
    sampled = np.zeros(k).astype(bool)
    infected[:x0] = 1
    while np.any(infected & ~sampled):
        arr = infected & ~sampled
        infecting_id = arr.nonzero()[0][0]
        sampled[infecting_id] = True
        probs = np.ones(k)
        probs[infecting_id] = 0
        probs /= (k - 1)
        infections = rng.binomial(k - 1, alpha)
        choices = rng.choice(k, infections, replace=False, p=probs)
        infected[choices] = True
    return sum(infected)

In [51]:
iterations=100000
print(f'k\talpha\texpected infected\t(iterations={iterations})')
for k in np.arange(2, 15):
    for alpha in np.arange(0.1, 1.0, 0.1):
        expected_infected = 0
        for iters in np.arange(iterations):
            infected = compute_number_of_infected(alpha, k)
            expected_infected = (expected_infected * iters + infected) / (iters + 1)
        print(f'{k}\t{alpha:.3f}\t{expected_infected:.4f}')

k	alpha	expected infected	(iterations=100000)
2	0.100	1.1004
2	0.200	1.1994
2	0.300	1.2988
2	0.400	1.4032
2	0.500	1.4999
2	0.600	1.6025
2	0.700	1.7011
2	0.800	1.8003
2	0.900	1.8969
3	0.100	1.2195
3	0.200	1.4657
3	0.300	1.7264
3	0.400	1.9910
3	0.500	2.2489
3	0.600	2.4861
3	0.700	2.6944
3	0.800	2.8562
3	0.900	2.9626
4	0.100	1.3554
4	0.200	1.8145
4	0.300	2.3149
4	0.400	2.8139
4	0.500	3.2436
4	0.600	3.5905
4	0.700	3.8200
4	0.800	3.9457
4	0.900	3.9929
5	0.100	1.5230
5	0.200	2.2635
5	0.300	3.1045
5	0.400	3.8437
5	0.500	4.4130
5	0.600	4.7565
5	0.700	4.9266
5	0.800	4.9865
5	0.900	4.9992
6	0.100	1.7250
6	0.200	2.8637
6	0.300	4.0767
6	0.400	5.0480
6	0.500	5.6157
6	0.600	5.8832
6	0.700	5.9751
6	0.800	5.9963
6	0.900	5.9999
7	0.100	1.9693
7	0.200	3.6004
7	0.300	5.2356
7	0.400	6.2956
7	0.500	6.7767
7	0.600	6.9456
7	0.700	6.9906
7	0.800	6.9991
7	0.900	7.0000
8	0.100	2.2521
8	0.200	4.5057
8	0.300	6.5063
8	0.400	7.5200
8	0.500	7.8825
8	0.600	7.9775
8	0.700	7.9966
8	0.800	7.9999
8	0.900	8.0000
9	0.100	2

In [9]:
import numpy as np
k=10
x0=3
v=np.zeros(k).astype(bool)
v[:x0]=1
v

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [6]:
sampled = np.zeros(k).astype(bool)

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [13]:
np.any(v & ~sampled)

True

In [14]:
v[~sampled]

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [18]:
v[~sampled].nonzero()[0][0]

0

In [19]:
sampled[0]=True

In [20]:
v[~sampled].nonzero()[0][0]

0

In [23]:
v[~sampled]

array([ True,  True, False, False, False, False, False, False, False])

In [25]:
v & ~sampled

array([False,  True,  True, False, False, False, False, False, False,
       False])

In [27]:
arr = v & ~sampled

In [28]:
arr.nonzero()

(array([1, 2]),)

In [29]:
probs = np.ones(k)
infecting_id = arr.nonzero()[0][0]
probs[infecting_id] = 0
probs /= (k - 1)
probs

array([0.11111111, 0.        , 0.11111111, 0.11111111, 0.11111111,
       0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111])

In [36]:
infections = 3
rng = np.random.default_rng()
choices = rng.choice(k, infections, replace=False, p=probs)

In [38]:
v[choices]

array([False, False,  True])

In [39]:
v

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [40]:
v[choices]=True

In [37]:
choices

array([7, 3, 0])

In [41]:
v

array([ True,  True,  True,  True, False, False, False,  True, False,
       False])

In [42]:
sum(v)

5